INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Champion Kids Hooded','17','https://m.media-amazon.com/images/I/71MGTC0lZGL._AC_UY550_.jpg','kids','Classic Champion Script Chest Logo - The signature Champion logo represents over 100 years of outfitting athletes and competitors.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Champion Boys Tee Shirt Kids Tops','12','https://m.media-amazon.com/images/I/81OuSE18WBL._AC_UX569_.jpg','kids','GUARANTEED AUTHENTIC CHAMPION APPAREL: No imitations, this is authentic Champion kids athletic apparel.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('PATPAT Kids ','18','https://m.media-amazon.com/images/I/712hmt54p3L._AC_UX569_.jpg','kids','Soft,comfortable and breathable fabric perfect for kids.Soft fabric to help protect childs delicate skin, very comfortable and durable to wear.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Aza Boutique Girls Cute Bunny Sweatshirt','23','https://m.media-amazon.com/images/I/51Eh-hTYAXL._AC_UX569_.jpg','kids','Material: Cotton Blend, Original and high quality'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('GAMISOTE Kids Girls Fuzzy Hoodies','25','https://m.media-amazon.com/images/I/71-9xGSuKeL._AC_UX466_.jpg','kids',' MATERIAL: Polyester, Soft, lightweight, comfy fluffy fleece, perfect for autumn/winter chilly days.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Sweater','25','https://m.media-amazon.com/images/I/71MwKOv8wuL._AC_UX569_.jpg','kids','QUALITY FABRIC: Kids pullovers made with super soft and skin friendly material, mid-weight comfy knitwear, perfect for spring fall winter wear'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('5-14 Years Boys Button Down Coat','23','https://m.media-amazon.com/images/I/6190rcVStcL._AC_UX569_.jpg','kids','Features: Boys casual coat shirts, button down, front patch pockets, long sleeve, turn-down collar, loose fit jacket, drop shoulder, single breasted The basic outerwear jackets is made 
of comfortable and skin-friendly fabric which is suitable for spring, fall and winter'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Carters Boys Fleece','20','https://m.media-amazon.com/images/I/81r4W61zkQL._AC_UX569_.jpg','kids','MONSTER SCREEN PRINT ON FRONT'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Kids Boys Girls Jacket','38','https://m.media-amazon.com/images/I/71yrkHbV9aL._AC_UX569_.jpg','kids','Adorable boys Jackets or hoodie, a breathable, soft, and comfortable Dark Yellow and Blue long-sleeves casual comfy warm zip up sweatshirt to keep them comfortable and warm'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Gihuo Unisex Boys Girls Winter Warm Sherpa Lined Crewneck Pullover Sweatshirt','28','https://m.media-amazon.com/images/I/816Xw16fvBL._AC_UX679_.jpg','kids','Pullover closure, Solid color, round neck'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('YAHUIUL Parachute Pants for Women','31','https://m.media-amazon.com/images/I/51PWAqcym0L._AC_UY550_.jpg','pants','Parachute pants for women are made of premium fabric, wearable, skin-friendly, soft, comfortable for all-day wear'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Amazon Essentials Mens Pant','15','https://m.media-amazon.com/images/I/71TOtMq54ML._AC_UX569_.jpg','pants','This slim-fit chino pant features wrinkle-free fabric, a flat-front design, and button-through back welt pockets for a tailored look and all-day comfort'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Arizona Tie Pant Womens, Safari, Large','50','https://m.media-amazon.com/images/I/71u0SkXi4cS._AC_UX569_.jpg','pants','Tie top, Skinny leg'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Monrow Womens Sporty Sweatpants','135','https://m.media-amazon.com/images/I/91QDOXMj5oL._AC_UY550_.jpg','pants','YOUR MOST FLATTERING SWEATPANT: With the same flattering straight leg cut as our classic vintage sweats, these sweatpants make things even comfier with a drawstring closure so that you can find your perfect fit.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Womens Supersoft Sweater Knit Cuffed Joggers','156','https://m.media-amazon.com/images/I/61ipowTQ9bL._AC_UX679_.jpg','pants','FOR MORE THAN LOUNGING: Cozy enough for the couch and still cute enough for errands. Gym, coffee, and dog walk approved.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Womens 90s Classic Joggers, Flattering Straight Leg Cut','168','https://m.media-amazon.com/images/I/51wTSayWD6L._AC_UX569_.jpg','pants','FOR MORE THAN LOUNGING: Cozy enough for the 
couch and still cute enough for errands. Great for everything from work-from-home days to casual coffee runs, workouts, and chill lunches out.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('CRZ YOGA Womens Sweatpants','34','https://m.media-amazon.com/images/I/71sL84JXI9L._AC_UY550_.jpg','pants','Inseam: 27 inches, intended to sit at ankle. High Waist. Semi-slim Fit'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Match Mens Wild Cargo Pants','40','https://m.media-amazon.com/images/I/51lrvBS8lRL._AC_UX569_.jpg','pants','Sits at waist / loose fit / straight legCold machine / hand wash separately Notice: Belt not included, please buy separately'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Good Man Brand Mens','148','https://m.media-amazon.com/images/I/61cMuT90+0S._AC_UX679_.jpg','pants','MODERN AND VERSATILE - You can only spend so much time behind a desk, and a day spent in motion is much more satisfying. Spend it looking good both in the office and on the move 
in your Pro Stretch Twill Star Chino casual pants for men.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Mens Golf Pants','47','https://m.media-amazon.com/images/I/71P0zVxGEcL._AC_UY550_.jpg','pants','62% cotton, comfortable breathable and moisture; 35% polyester, prevent color fading and being out of shape to make sure the bright vivid color and good shape; 3% spandex, offer stretch room for golf sports'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Janet Band Jackson T-Shirts','23','https://m.media-amazon.com/images/I/61nCOKK2i5L._AC_UX569_.jpg','shirt','100% Cotton.The Selection Of Environmentally Friendly Fabrics Allows You To Dress More Comfortably.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('The Drop Womens Sydney Short-sleeve Cropped Crew Neck T-shirt','19','https://m.media-amazon.com/images/I/91vmWaCA58L._AC_UY550_.jpg','shirt','Staples by The 
Drop'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('BELONGSCI Womens Dress Sweet','14','https://m.media-amazon.com/images/I/51ZjAjaaW1L._AC_UX522_.jpg','dress','Perfect outfit for summer and autumn daily wear, school, casual, beach, vacation, date, party, club, etc.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Amoretu Women Summer Tunic Dress','26','https://m.media-amazon.com/images/I/61UQcTVpA1L._AC_UY550_.jpg','dress','Deep v neckline with lantern long sleeve/short sleeve/sleeveless, super sexy, fashionable and elegant.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('ECOWISH Women','30','https://m.media-amazon.com/images/I/71aVecbFY1L._AC_UY550_.jpg','dress','Material - This long sleeve fall dress is made of VISCOSE. You will feel comfortable to skin, soft and breathable.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('MEIZHINV Women Summer Casual Dress','32','https://m.media-amazon.com/images/I/619KhyOJ8hL._AC_UX466_.jpg','dress','Material: 100% Polyester. Breathable And Comfortable, Skin-Friendly And Comfy To Wear, Bringing You A Pleasant Dressing Experience.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('FARYSAYS Womens Dresses','37','https://m.media-amazon.com/images/I/61w8s7vS-0L._AC_UY550_.jpg','dress','Feature: Ruffle, Waist Tie, Round Neck, Long Sleeve, Elastic Waist, Back Hole, A-Line, Swing Flared, Above Knee Length, Casual mini dresses fits for any body shape.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('BELONGSCI Womens Dress Sweet','32','https://m.media-amazon.com/images/I/51vroLbml5L._AC_UX522_.jpg','dress','Dressy cute dress, V-neck, long sleeve, mini short dress, nice material and comfortable,non-see through,casual perfect fitting, best choice for casual/wedding/cocktail/party/work/ business. Suitable for spring and summer wear.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Nike Womens Basketball Shoe','120','https://m.media-amazon.com/images/I/613HmnmaO6L._AC_UX575_.jpg','shose','Womens Basketball Shoes'); 
INSERT INTO products (title,price,imgUrl,category,description) 
VALUES ('Nike Womens Race Running Shoe','141','https://m.media-amazon.com/images/I/61aDXpWqAEL._AC_UY575_.jpg','shose','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has 
been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Nike Zoom Air Fire Womens Running Trainers Cw3876 Sneakers Shoes','105','https://m.media-amazon.com/images/I/71+02iaGsKL._AC_UY695_.jpg','shose','Lorem Ipsum is simply dummy text of the printing and typesetting industry.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Nike Womens Quest 3 Running Shoe','98','https://m.media-amazon.com/images/I/61wa7SuCzxL._AC_UX575_.jpg','shose','Lorem Ipsum is simply dummy text of the printing and typesetting industry.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Agirlvct Pearl Hair Claw','10','https://m.media-amazon.com/images/I/71UVPFOnT4L._SX466_.jpg','accessories','Big Hair Clips Barrettes Nonslip Birthday Business Gift 
Hair Accessories for Women Girls Daughter Girlfriend(4 Pack)'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Unicra Leaf Wedding Hair Vine Flower','0','https://m.media-amazon.com/images/I/61o-IUIh50L._AC_SX679_.jpg','accessories','Rose gold leaves hair accessories in unique design and excellent workmanship, made of flowers, crystals, rhinestones, and alloy.'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('6 Pieces Pearl ','8','https://m.media-amazon.com/images/I/71GiTLq7q4S._SX466_.jpg','accessories','What you receive: 6 pieces of bride hair pins in total, these simple and classical hair pins are good for wedding, prom and party'); 
INSERT INTO products (title,price,imgUrl,category,description) VALUES ('Jakawin Bride Wedding Pearl Hair ','13','https://m.media-amazon.com/images/I/61RVJHFW7FL._SX466_.jpg','accessories','Wedding hair pins are made of alloy,pearls, beads and crystal rhinestone.');